### ISSUE TITLE
Document the { equals } option for signals

### ISSUE THREAD

**Issue by EmNudge** [solidjs/solid-site#119]
This property is necessary to get performant reactivity on any large object (we don't need to spread it to create a new reference), but it was not mentioned in the tutorial nor in the docs. The docs show typings for it, but no reason for why it might be needed.

Placing its use in the tutorial as well as in the docs would be a massive help.

**Comment by davedbase** [comment]
Summoning @ryansolid as we need his opinion on this.

**Comment by ryansolid** [comment]
Yeah it's more complicated than that. Because you need propagate the change all the way through. As it's going to again get caught on the first downstream memo that does equality check (the default). I think it has its use but it also is one of those things that can easily break if you use it as your go-to pattern. I think we do need to document it, but probably something simple to explain the usage and not sell it as a benefit. It's sort of a neutral thing, and now the way Solid's defaults are (not previously) one that can be a bit dangerous. But I also don't think we need to be heavy-handed with a warning. It should just be.

All Signals/Memos have this option wasn't sure how to manage that. Because putting it under each seems excessive. Maybe have a Signal options note under basics.. I think that is why it was absent, I wasn't sure where to put it, and forgot by the time was done.
