### ISSUE TITLE
Optimize worker data list

### ISSUE THREAD

**Issue by davedbase** [solidjs/solid-site#209]
Hi @userquin, just noticing that the workers tend to pull in all the site chunks/dependencies. That's generally fine but it seems like it's being aggressive and pulling in far more than it actually needs as soon as you hit the site. For example we chunk up our language specific files in a manner that makes them easy to deploy.

The issue is that the site is now pulling down 50mb of data for every user.

<img width="1277" alt="Screen Shot 2021-12-24 at 11 51 24 AM" src="https://user-images.githubusercontent.com/1168397/147365530-6296f365-2e02-4606-83e8-d658ebec3d4c.png">

Is there a way to dynamically/selectively only pull the language chunks that are relevant? Perhaps we need to consider a different strategy overall to what's available for offline access?

**Comment by userquin** [comment]
All entries should be precache and is done by the sw, there is no problem at all since the requests are in backgorund thread. You should also add some compression gzip and/or brotli. 

The pwa works this way, so you can omit some resources such as vídeos or some images to reduce the size, but beware that the resource containing the page works without these resources. You can use globIgnore or transformManifest function on workbox entry to omit some resource.

**Comment by davedbase** [comment]
Thanks for the insight. I suppose my concern is that ALL languages of docs and tutorials are also be unnecessarily cached. I'm hoping to find a way to only cache the relevant language of the user. The full payload of cached assets bloats to about 50mb when in reality it should be something closer to 5-10mb.

**Comment by userquin** [comment]
@davedbase do you need help to do it? If so just ping me, when I have time I can take a look (very busy with `vitest`).

**Comment by davedbase** [comment]
@userquin thanks so much! I'll be honest with you SWs aren't my strength and I've only ever implemented it once on a much smaller build. I also don't want you taking time away from vitest (please focus on that we want vitest! haha) however if you had a few moments to describe how the solution could work, there are other community members with SW and Workbox experience that could pick up the effort.

**Comment by userquin** [comment]
@davedbase you only need to filter the files included from the dist folder, since workbox will just add it to the sw precache manifest (`selft.__SW_MANIFEST`). It can be done using `globIgnores` option (similar to regex, using node-glob)  or adding `transformManifest` hook, both on `workbox` option of the `vite plugin pwa` configuration: see https://developers.google.com/web/tools/workbox/reference-docs/latest/module-workbox-build#.generateSW

For `transformManifest`, you can take a look at this project, basically you only need to remove from the manifest the entries you don't want (on the example, we don't remove anything, we are just transforming the url for sveltekit routes, that should include name of the folder, that's, the logical name for the router): https://github.com/antfu/vite-plugin-pwa/blob/main/examples/sveltekit-pwa/pwa-configuration.js#L52

**Comment by userquin** [comment]
@davedbase FYI: I also added an example on `unocss` (if you don't see my tweet): https://twitter.com/Joaqun70556742/status/1474373823235563525

**Comment by davedbase** [comment]
@userquin hah awesome! We're using unocss in Solid Primitives actually. Loving it. I hate to report to you that unfortunately the wrong Solid logo was used. That's the Solid logo from Tim Berner Lee's project, not us. Hehe. You can find our logo and brand assets here: https://www.solidjs.com/media

If you update + retweet I'll have Ryan retweet it. :-)

**Comment by userquin** [comment]
@davedbase upps sorry for the logo, we use the logo  from `@iconify-json/logos` in all our project examples (react, preact, svelte, sveltekit, vue, nuxt, solid, lit)

**Comment by davedbase** [comment]
Ah yes, you should use `solidjs-icon` which is already in the package. Should be an easy fix! =)

**Comment by userquin** [comment]
@davedbase also the same name on twitter?

![imagen](https://user-images.githubusercontent.com/6311119/147862184-959ab07a-87e8-4b35-a7da-aa684f0119f5.png)
