### ISSUE TITLE
Feature Request: Store Playground Content In Cookie Or Local Storage

### ISSUE THREAD

**Issue by fweth** [solidjs/solid-site#288]
Hi, it would be great if the content of the playground is stored somewhere so I can go back to what I previously built, without manually saving it.  Alternatively, it could be saved on the server similarly to JSFiddle, with a custom link, so that snippets can be more easily shared on the web.  But the first variant should be much easier to implement.

**Comment by edemaine** [comment]
This is an issue for [solid-playground](https://github.com/solidjs/solid-playground/); check out that repo for other related proposals.

In particular, instead of localstorage, I think [this proposal](https://github.com/solidjs/solid-playground/issues/105#issuecomment-1130144932) would satisfy you (persist content over reloads). Feel free to leave a comment there!

Note also that, right now, if you click the "share" button, you'll get a custom link in your clipboard, which is used a lot for sharing!

**Comment by fweth** [comment]
Thanks for the answer and sorry for posting to the wrong repository!  Yes, custom link is great, I didn't discover that.  I still think it would be cool to be able to close the tab for whatever reason (browser crashing, etc.) and not losing your work, dartpad.dev does a great job I think.  Feel free to close the issue!

**Comment by edemaine** [comment]
Ah, fair point: localstorage is nice for remembering longer term like that.  I notice that most other playgrounds do that, and it's kind of neat to see what I was working on last time.  Maybe you want to open that specific suggestion on the playground repo?  Meanwhile I'll close this one.
