### ISSUE TITLE
Ukranian localization

### ISSUE THREAD

**Issue by djleonskennedy** [solidjs/solid-site#296]
I'm living in Ukraine

After opening the site I have russian language, is it possible to add Ukrainian language or use English instead of russian?

**Comment by edemaine** [comment]
That's definitely not intentional! Ukrainian translations were added recently. For manual override, do you see the language button at the end of the top nav? (The funny character in the top right.)

![image](https://user-images.githubusercontent.com/2218736/169715348-6eb02b6b-73cd-4350-8009-9742f7e2e832.png)

I'm not sure how the language automatic detection works (IP -> country?); perhaps others can comment on that.

**Comment by djleonskennedy** [comment]
@edemaine Thank you
